# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NoktaKontrol
                                 A QGIS plugin
 60 cm den yakın noktaları bulma
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-10-03
        copyright            : (C) 2018 by aylin.torun
        email                : aylin.torun@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NoktaKontrol class from file NoktaKontrol.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nokta_kontrol import NoktaKontrol
    return NoktaKontrol(iface)
    from OtherWindow import Ui_OtherWindow